"""align session_summaries columns with model

Revision ID: 15998d67a6f2
Revises: 675b74e56988
Create Date: 2026-06-08 21:54:39.621578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15998d67a6f2'
down_revision: Union[str, Sequence[str], None] = '675b74e56988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_episodic_embedding'), table_name='episodic_memory', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_procedural_embedding'), table_name='procedural_memory', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_rag_chunks_embedding'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('session_summaries', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_summaries', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_rag_chunks_embedding'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_procedural_embedding'), 'procedural_memory', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_episodic_embedding'), 'episodic_memory', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
