"""bi-temporal codex edges: learned_at / unlearned_at (G45)

Revision ID: 505f12031434
Revises: f2a7c9e04b31
Create Date: 2026-08-13 16:59:40.598734

⚠ **THE AUTOGENERATED BODY WAS DISCARDED. READ THIS BEFORE REGENERATING.**
`--autogenerate` proposed dropping **every HNSW vector index in the database**
(`idx_episodic_memory_embedding`, `idx_codex_entities_embedding`,
`idx_episodic_chunks_embedding`, `idx_context_clusters_embedding`,
`idx_decisions_embedding`, `idx_batch_summaries_embedding`,
`idx_procedural_memory_embedding`) plus a dozen btree indexes including G6's,
`uq_memory_slots_name_tier_anchor`, and the partial indexes — and flipping half
a dozen columns to nullable.

None of that is a real schema change. Those objects are created by raw SQL in
earlier migrations and are not declared on the models, so autogenerate sees them
as drift and "corrects" them. Applying it would have silently removed every
vector index in the store — retrieval would still work and simply get slower,
which is the worst kind of regression to catch. TRAPS #14 exists for exactly
this; the fix is to keep only the intended lines.

This migration therefore does ONE thing: add the two bi-temporal columns.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '505f12031434'
down_revision: Union[str, Sequence[str], None] = 'f2a7c9e04b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the learned/unlearned timeline to codex_edges.

    `valid_from`/`valid_until` say when the FACT was true. These say when ICE
    believed it. Existing rows are backfilled from `valid_from` — the honest
    approximation, since for a row written by extraction the moment we learned
    it IS the moment we recorded it; there is no better answer available and
    leaving them NULL would read as "never learned".
    """
    op.add_column('codex_edges',
                  sa.Column('learned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('codex_edges',
                  sa.Column('unlearned_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE codex_edges SET learned_at = valid_from "
               "WHERE learned_at IS NULL")
    # Rows already retracted (valid_until set) stopped being believed then.
    op.execute("UPDATE codex_edges SET unlearned_at = valid_until "
               "WHERE valid_until IS NOT NULL AND unlearned_at IS NULL")
    op.create_index('ix_codex_edges_learned', 'codex_edges',
                    ['learned_at', 'unlearned_at'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_codex_edges_learned', table_name='codex_edges')
    op.drop_column('codex_edges', 'unlearned_at')
    op.drop_column('codex_edges', 'learned_at')
