"""add embedding column to codex_entities

Revision ID: 5b14dcf3b0b9
Revises: db1eba0e52a8
Create Date: 2026-06-19 22:11:34.284548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5b14dcf3b0b9'
down_revision: Union[str, Sequence[str], None] = 'db1eba0e52a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codex_entities', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codex_entities', 'embedding')
    # ### end Alembic commands ###
