"""add inject_raw column and review_queue table

Revision ID: 6255412d7bb1
Revises: 3ef48b581c11
Create Date: 2026-06-10 13:41:08.836874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6255412d7bb1'
down_revision: Union[str, Sequence[str], None] = '3ef48b581c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_queue', 'item_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('review_queue', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('review_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_queue', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('review_queue', 'item_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
