"""initial schema

Revision ID: 675b74e56988
Revises: 
Create Date: 2026-06-06 16:39:26.648810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '675b74e56988'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codex_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_payload', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('cold_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('topic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memory_scope_type', sa.Text(), nullable=False),
    sa.Column('cluster_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('custom_filter', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curated_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('corrected_topic_labels', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('corrected_intent_labels', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('corrected_context_reliance', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('memory_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedural_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pattern_name', sa.Text(), nullable=False),
    sa.Column('pattern_description', sa.Text(), nullable=True),
    sa.Column('topic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reinforcement_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('first_observed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('source_batch_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentinel_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codex_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('source_batch', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['codex_entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['codex_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codex_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_source', sa.UUID(), nullable=False),
    sa.Column('compacted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['codex_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codex_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.UUID(), nullable=False),
    sa.Column('full_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['codex_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodic_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('intent_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('context_reliance', sa.Text(), nullable=False),
    sa.Column('entropy_score', sa.Float(), nullable=True),
    sa.Column('lossless_flag', sa.Boolean(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('decay_score', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True),
    sa.Column('decay_immune', sa.Boolean(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['context_clusters.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['episodic_memory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('rag_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentinel_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['sentinel_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_replays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('event_sequence', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('topics_covered', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('decisions_made', sa.Text(), nullable=True),
    sa.Column('unresolved_items', sa.Text(), nullable=True),
    sa.Column('entities_updated', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('patterns_observed', sa.ARRAY(sa.UUID()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_summaries')
    op.drop_table('session_replays')
    op.drop_table('sentinel_events')
    op.drop_table('rag_chunks')
    op.drop_table('episodic_memory')
    op.drop_table('codex_snapshots')
    op.drop_table('codex_events')
    op.drop_table('codex_edges')
    op.drop_table('sentinel_rules')
    op.drop_table('rag_documents')
    op.drop_table('procedural_memory')
    op.drop_table('memory_slots')
    op.drop_table('idempotency_keys')
    op.drop_table('curated_labels')
    op.drop_table('conversations')
    op.drop_table('context_clusters')
    op.drop_table('cold_storage')
    op.drop_table('codex_entities')
    # ### end Alembic commands ###
