"""add embedding column to context_clusters

Revision ID: 7c35ee6e2e59
Revises: 57d189f5f508
Create Date: 2026-06-20 12:15:09.621948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7c35ee6e2e59'
down_revision: Union[str, Sequence[str], None] = '57d189f5f508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_clusters', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_clusters', 'embedding')
    # ### end Alembic commands ###
