"""add is_document column to episodic_memory

Revision ID: b0e78d3828da
Revises: 5b14dcf3b0b9
Create Date: 2026-06-20 12:02:51.174253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e78d3828da'
down_revision: Union[str, Sequence[str], None] = '5b14dcf3b0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodic_memory', sa.Column('is_document', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodic_memory', 'is_document')
    # ### end Alembic commands ###
