"""batch-summary coverage marker on episodic turns (G11)

Revision ID: d5c81a37e9b2
Revises: c704abf1917e
Create Date: 2026-08-08

HAND-WRITTEN, not autogenerated — see the `c704abf1917e` header for why
(`--autogenerate` proposes dropping every index the ORM models do not declare,
which is all seven HNSW vector indexes plus the partial/composite ones built by
raw SQL). This revision adds exactly one column, one FK and one index.

WHY (roadmap G11): `batch_summarize` selected turns by decay score with nothing
excluding turns it had already summarised — while its own docstring claimed it
found turns "that haven't been batch-summarised". Each cadence pass therefore
re-ran the LLM over the same turns and appended another `batch_summaries` row,
and the batch-summary retrieval leg injected the duplicates. The existing
`start_turn_index` / `end_turn_index` columns cannot serve as the coverage
record: they are positions in the filtered, decay-ordered list that the
producing run happened to build, and that list changes between runs.

ON DELETE SET NULL is deliberate: deleting a summary (C10's cascade does, per
conversation) must make its turns eligible for summarising again rather than
orphaning the reference or blocking the delete.

Backfill: none, and that is correct. Existing rows get NULL, i.e. "not yet
summarised" — which for a store whose summaries were already duplicated is the
honest starting state, and re-summarising once under the new guard converges.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5c81a37e9b2"
down_revision: Union[str, None] = "c704abf1917e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "episodic_memory",
        sa.Column("batch_summary_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_episodic_memory_batch_summary_id",
        "episodic_memory", "batch_summaries",
        ["batch_summary_id"], ["id"],
        ondelete="SET NULL",
    )
    # The selection predicate is `batch_summary_id IS NULL`, so the index is
    # partial — it only ever needs to find the unsummarised rows, and that set
    # shrinks over time while the table grows.
    op.create_index(
        "idx_episodic_memory_unsummarised",
        "episodic_memory", ["timestamp"],
        postgresql_where=sa.text("batch_summary_id IS NULL"),
    )


def downgrade() -> None:
    op.drop_index("idx_episodic_memory_unsummarised",
                  table_name="episodic_memory")
    op.drop_constraint("fk_episodic_memory_batch_summary_id",
                       "episodic_memory", type_="foreignkey")
    op.drop_column("episodic_memory", "batch_summary_id")
