"""DI3 configuration loader – reads from api/config.py or uses defaults."""

try:
    from src.api.config import settings

    DI3_ENABLED = getattr(settings, "DI3_ENABLED", True)
    DI3_CODE_DENSITY_THRESHOLD = getattr(settings, "DI3_CODE_DENSITY_THRESHOLD", 0.3)
    DI3_SENTIMENT_DENSITY_THRESHOLD = getattr(settings, "DI3_SENTIMENT_DENSITY_THRESHOLD", 0.4)
    DI3_META_DENSITY_THRESHOLD = getattr(settings, "DI3_META_DENSITY_THRESHOLD", 0.2)
    DI3_NOISE_DENSITY_THRESHOLD = getattr(settings, "DI3_NOISE_DENSITY_THRESHOLD", 0.8)
    DI3_REFERENCE_DENSITY_THRESHOLD = getattr(settings, "DI3_REFERENCE_DENSITY_THRESHOLD", 0.2)
    DI3_LTM_REFERENCE_DENSITY_THRESHOLD = getattr(settings, "DI3_LTM_REFERENCE_DENSITY_THRESHOLD", 0.1)
except ImportError:
    DI3_ENABLED = True
    DI3_CODE_DENSITY_THRESHOLD = 0.3
    DI3_SENTIMENT_DENSITY_THRESHOLD = 0.4
    DI3_META_DENSITY_THRESHOLD = 0.2
    DI3_NOISE_DENSITY_THRESHOLD = 0.8
    DI3_REFERENCE_DENSITY_THRESHOLD = 0.2
    DI3_LTM_REFERENCE_DENSITY_THRESHOLD = 0.1